name: Fetch Odds & Upsert Props

on:
  schedule:
    - cron: '0 2 * * *'      # Runs daily at 02:00 UTC
  workflow_dispatch:        # Allows manual trigger

jobs:
  fetch-props:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: List repo contents (debug)
        run: ls -R .

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm ci

      - name: Run fetchOdds script
        env:
          NEXT_PUBLIC_SUPABASE_URL:      ${{ secrets.SUPABASE_URL }}
          SUPABASE_SERVICE_ROLE_KEY:     ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}
          ODDS_API_KEY:                  ${{ secrets.ODDS_API_KEY }}
        run: node scripts/fetchOdds.js
